name: CI Pipeline

on:
  push:
    branches: 
      - main
      - master
      - develop
  pull_request:
    branches: 
      - main
      - master
      - develop

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm' # NPM cache for faster builds

      - name: Install dependencies
        run: npm ci # Prefer npm ci for cleaner and reproducible builds

      - name: Run Tests
        run: npm test

      - name: Upload Test Results (Optional)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: playwright-report # Assuming test results are here
